#!/bin/sh

run_test() {
    dmypy run -- manabi || return
    flake8 manabi || return
    pytest manabi || return
}

run_test
while inotifywait -q -r -e create,modify,delete manabi; do
    run_test
done
