version: "3.8"
services:
  db:
    image: postgres:alpine
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: manabi
      POSTGRES_USER: manabi
      POSTGRES_DB: manabi
    ports:
      - "5432:5432"
