version: "3.8"
services:
  web:
    restart: "unless-stopped"
    build: .
    ports:
      - "80:8081"
  db:
    image: postgres
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: manabi
      POSTGRES_USER: manabi
      POSTGRES_DB: manabi
    ports:
      - "5432:5432"
