version: "3.8"

services:

  db:
    image: postgres:alpine
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: manabi
      POSTGRES_USER: manabi
      POSTGRES_DB: manabi
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: veryvery
      MINIO_ROOT_PASSWORD: secretsecret
      MINIO_BROWSER: on
    command: server data --console-address ":9090"

  mc:
    image: minio/mc:latest
    environment:
      MINIO_ROOT_USER: veryvery
      MINIO_ROOT_PASSWORD: secretsecret
    entrypoint: >
      /bin/sh -c "
      mc config host add dc-minio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} --api S3v4;
      mc mb dc-minio/manabi-media;
      true"
    depends_on:
      - minio

volumes:
  minio_data:
    driver: local
