#!/bin/sh

set -e
mkdir /home/manabi
chown manabi:manabi /home/manabi
chown -R manabi:manabi /app

export DEBIAN_FRONTEND=noninteractive
apt-get -y update
apt-get -y install libpq-dev git sudo libsodium23 python3-pip build-essential

sudo -u manabi c/pipinstall

apt-get -y purge git python3-pip build-essential
apt-get -y autoremove
apt-get clean
rm -rf /var/cache/apt
