#!/bin/sh

. c/config
VERSION=$MANABI_IMAGE_VERSION
IMAGE_BASE="acr.run/camac-ng/manabi"
if ! docker pull $IMAGE_BASE:v$VERSION; then
    . c/increment_check
    set -e
    # The image may be cached, build should recognice this, but I want to
    # display a message
    if ! docker image inspect $IMAGE_BASE:p$CI_PIPELINE_ID > /dev/null; then
        docker build -f Dockerfile.build -t $IMAGE_BASE:p$CI_PIPELINE_ID .
    else
        echo Using cached $IMAGE_BASE:p$CI_PIPELINE_ID
    fi
    docker build --build-arg VERSION=p$CI_PIPELINE_ID -t test .
else
    set -e
    docker build --build-arg VERSION=v$VERSION -t test .
fi

docker run test pipenv run "$@"
